### ISSUE TITLE
Color issue with Shader

### ISSUE THREAD

**Issue by Drehverschluss** [Vazkii/Neat#13]
Hello there.

I just saw that your mod seems to flicker around when a shader is aktiv. So like the Color always changing around when i move my mouse. I dont know if thats possible to fix by you but i just left a comment here.

OptiFine_1.9.4_HD_U_B4 - for 1.9.4
SEUS-v10.2-Preview-1-Ultra - Shader i am using

MFG

**Comment by JezzX** [comment]
Just wanted to say I also get this issue and it  kind of makes the mod unusable which is a shame because its just what I wanted
And I'm using the newer SEUS 11.0 shader

**Comment by Vazkii** [comment]
I don't support optifine.
