### ISSUE TITLE
Visual bug with unstable blocks and "Neat" Mod

### ISSUE THREAD

**Issue by Myknakryu** [Vazkii/Neat#14]
Propably I should earlier post it there but. I was hoping that the glitch was known to you before. But when new version of Neat came out it didn't fix the problem. So now i'm posting it there

With the newest Forge 1954, Botania Unofficial 308, Neat 1.2-9; bug still happens.

There some old screenshots of this. Note that this is still happening in newer versions of those mods.
http://imgur.com/a/UfAHp

**Comment by Vazkii** [comment]
Should be fixed with https://github.com/Vazkii/Neat/commit/e5a6a390ef61458cb24c71950e79f843eebe68cb
