### ISSUE TITLE
Blacklist Config Update

### ISSUE THREAD

**Issue by SextupleTap** [Vazkii/Neat#38]
As of now the system for blacklisting entities is a bit rough, for example whilst using the Primitive Mobs mod I am trying to blacklist the Lily Lurker entity, but no matter what I input/combination I use for the entity name, I can't get Neat to detect the entity and hide the name tag. It would be useful for the blacklist feature to have the extended functionality of being able to detect entities with the 'modid:entityname' format along side the current system in place (as of Neat 1.4-17.jar).

**Comment by Vazkii** [comment]
Having F3 up and looking at an entity shows its ID.
