### ISSUE TITLE
Interference with Botania 1.8 wisp particles

### ISSUE THREAD

**Issue by williewillus** [Vazkii/Neat#4]
This is more aimed at @61352151511 since they ported it to 1.8.x:

If a Neat unit frame and any Botania wisp particle is on screen at the same time, the wisp particle loses all of its alpha transparency. 
I'm not sure whose fault it is, Neat for not cleaning GL state or Botania 1.8 not setting it correctly, so opening an issue on both. See https://github.com/williewillus/Botania/issues/38

**Comment by 61352151511** [comment]
Where my port does the exact same calls as the 1.7 version it may have existed from the start, check and see if it does this with 1.7.10 botania and neat

**Comment by yrsegal** [comment]
Can confirm, it does not.
